services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./data/postgres:/var/lib/postgresql/data

    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n

    ports:
      - "${N8N_PORT}:5678"

    environment:
      TZ: ${TZ}
      NODE_FUNCTION_ALLOW_EXTERNAL: "@mozilla/readability,linkedom"

      # DATABASE CONFIG
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./data/n8n:/home/node/.n8n

    depends_on:
      - postgres

    restart: unless-stopped

  #llama 3.2 LLM
  ollama:
    image: ollama/ollama:latest
    container_name: ollama

    ports:
      - "11434:11434"

    volumes:
      - ./data/ollama:/root/.ollama

    restart: unless-stopped

  # Open WebUI - platform for interacting with LLMs
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui

    ports:
      - "3000:8080"

    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

    volumes:
      - ./data/open-webui:/app/backend/data

    depends_on:
      - ollama

    restart: unless-stopped


